AWS VPC and EKS - Terraform
Error on Terraform apply:


Error: Invalid count argument

  on .terraform/modules/eks-cluster-dev/data.tf line 17, in data "aws_ami" "eks_worker":
  17:   count = local.worker_has_linux_ami ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.


Error: Invalid count argument

  on .terraform/modules/eks-cluster-dev/data.tf line 30, in data "aws_ami" "eks_worker_windows":
  30:   count = local.worker_has_windows_ami ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.